### ISSUE TITLE
Issue: No support for characters in other keyboard layouts

### ISSUE THREAD

**Issue by DaGaBrokenHeart** [mavvos/SpotifyGlobal#4]
The issue appears when using the "/" key in the numpad. I wanted to use the numpad only for the controls. + to volume up, - to volume down, * for start-stop and / to change track.
The / key lowers de volume always. Even if it's not used in the "options.txt" file. The rest of the keys works flawlesly
PD: If i put any other key to change track, works as intended, but even then, the "/" key lowers always the volume.

**Comment by mavvos** [comment]
I was unable to replicate this bug, while using both the default hotkeys or the given hotkeys, tested in older SpotifyGlobal versions and on the current build.
```
VolUp=+
VolDown=-
PrevTrack=;
NextTrack=/
PlayPause=*
Back5s=shift+1
Forward5s=shift+3
Like=shift+7
Quit=shift+9
```
All working as intended on my end. Please provide more information about what version of Spotify and SpotifyGlobal you are using, and if you running the executable or python script.

**Comment by DaGaBrokenHeart** [comment]
Both versions are the latests.
Is the executable file.
Maybe is the language of the keyboard. Actually on ES-es. From Spain.

**Comment by mavvos** [comment]
> Maybe is the language of the keyboard. Actually on ES-es. From Spain.

Yep, this is the reason. Tested with ENG-us and PT-br keyboard layouts, only happens in ES keyboards.
Seems like both **/** and **-** are mapped to the same key in the keyboard module(??, guessing here, no clue), and because of this any hotkey set to **-** will also trigger when pressing **/**, weirdly enough, you can not set the **/** key separately as it will simply not work, not even when pressing **-**

My advice is just avoid using those keys as it is probably a problem with the library and there's very few I can do.

**Comment by DaGaBrokenHeart** [comment]
Ok, i really appreciated your effort :) I will use another key.
Thanks :) And btw, i love the program <3
